### ISSUE TITLE
Error at launch

### ISSUE THREAD

**Issue by Gazous** [ilcato/homebridge-Fibaro-HC2#10]
[6/5/2016, 2:12:24 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/5/2016, 2:12:24 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:51826
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:58:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:155:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:480:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:92:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:10)

**Comment by ilcato** [comment]
EADDRINUSE means that you are running homebridge two times; kill existing running instances of homebridge before launching another.

**Comment by Gazous** [comment]
Hi ilcato and thanks for your help.
Now I have another issue at launch

[6/6/2016, 12:55:18 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/6/2016, 12:55:18 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/6/2016, 12:55:18 PM] [FibaroHC2] Server Listening...
[6/6/2016, 12:55:18 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/6/2016, 12:55:18 PM] [FibaroHC2] Adding Accessory: Porte
[6/6/2016, 12:55:18 PM] [FibaroHC2] Adding Accessory: Porte
[6/6/2016, 12:55:18 PM] [FibaroHC2] Error getting data from Home Center: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 270cfb42-d061-438c-b0af-e11b620b75be undefined

I have deletes accessories and persist folders.
Any Idea ?

**Comment by ilcato** [comment]
Yes, you have two or more devices in Fibaro Home Center with the same name. Unfortunately the current version of the plugin requires a different name for each devices even if they are in different rooms.

**Comment by Gazous** [comment]
OK ! That's annoying because I have lots of devices with same name... Previous version was working with that. Why this limitation ?

**Comment by ilcato** [comment]
Because of a change in the plugin 2.0 architecture. I have a beta version that should work in you scenario. Would you like to test it?

**Comment by Gazous** [comment]
Why not !

**Comment by ilcato** [comment]
replace index.js file with the following [one](https://raw.githubusercontent.com/ilcato/homebridge-Fibaro-HC2/master/index.js).
If you are on a raspberry it should be in:
 `/usr/local/lib/node_modules/homebridge-fibaro-hc2`

**Comment by Gazous** [comment]
Thanks but just made a test and having same issue...

**Comment by ilcato** [comment]
Did you remove the accessories folder?

**Comment by Gazous** [comment]
Yes

**Comment by ilcato** [comment]
Now it should work. Download the file again from the previous link and reinstall it.

**Comment by Gazous** [comment]
Ok ! It seems to work better but now HC2 Device fetching is blocking on 3rd accessory...

[6/6/2016, 3:00:32 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/6/2016, 3:00:32 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/6/2016, 3:00:32 PM] [FibaroHC2] Server Listening...
[6/6/2016, 3:00:32 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/6/2016, 3:00:32 PM] [FibaroHC2] Adding Accessory: Porte
[6/6/2016, 3:00:33 PM] [FibaroHC2] Adding Accessory: Porte
[6/6/2016, 3:00:33 PM] [FibaroHC2] Adding Accessory: Volets

**Comment by ilcato** [comment]
try to run it again after removing the accessories folder in .homebridge

**Comment by Gazous** [comment]
Same behavior, strange !

**Comment by ilcato** [comment]
and if you run it again without removing the accessories folder in .homebridge ?
How do you run homebridge?

**Comment by Gazous** [comment]
without removing accessories folder, blocking like this

[6/6/2016, 3:33:39 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/6/2016, 3:33:39 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/6/2016, 3:33:39 PM] [FibaroHC2] Server Listening...
[6/6/2016, 3:33:39 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...

I run home bridge manually

**Comment by ilcato** [comment]
Can you run it by prefixing the following before the homebridge keyword: `DEBUG=*`

It should write more info on the log.

**Comment by Gazous** [comment]
Hi ilcato, I tried that but I have no more information regarding the issue

  Accessory [Homebridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Homebridge] Creating new IdentifierCache +24ms
[6/8/2016, 1:44:55 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/8/2016, 1:44:55 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/8/2016, 1:44:56 PM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +166ms
[6/8/2016, 1:44:56 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/8/2016, 1:44:56 PM] [FibaroHC2] Adding Accessory: Porte
[6/8/2016, 1:44:56 PM] [FibaroHC2] Adding Accessory: Porte
[6/8/2016, 1:44:56 PM] [FibaroHC2] Adding Accessory: Volets

**Comment by ilcato** [comment]
Do you have more than one device called "Volets"?
Can you send me (via private message) your devices list by entering the following URL:

http://HOMECENTER_ADDRESS/api/devices

**Comment by Gazous** [comment]
Yes I have severals devices name "Volet" but only one name "Volets". i don't find how tu send a private message. You can see my list of devices here : https://www.dropbox.com/s/fb4e56eqs4rfka4/Devices.json?dl=0

**Comment by Gazous** [comment]
Hello, I made a test by removing "Volets" devices from authorization and I have this

[6/10/2016, 10:22:57 AM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/10/2016, 10:22:57 AM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +166ms
[6/10/2016, 10:22:57 AM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/10/2016, 10:22:57 AM] [FibaroHC2] Adding Accessory: Porte
[6/10/2016, 10:22:57 AM] [FibaroHC2] Adding Accessory: Porte
[6/10/2016, 10:56:08 AM] [FibaroHC2] Error fetching updates: null

**Comment by ilcato** [comment]
Can you send also the rooms layout?

http://HOMECENTER_ADDRESS/api/rooms

**Comment by ilcato** [comment]
Can you also send your config.json (without credential off course)

**Comment by Gazous** [comment]
Hi, you will find the asked files at this address : https://www.dropbox.com/sh/8yzah0a4xbio9ge/AADius1j-58wdAS9l1hLIRCQa?dl=0
I am able to add it but don't see all devices.
Thanks for your help !

**Comment by ilcato** [comment]
Which devices is able to see the homebridge user in HC2?

**Comment by Gazous** [comment]
Good question, I just added a new file "Devices - homebridge user.json" in the shard folder.
node.js version is 4.00. I am on an RPI2. Everithing was working fine with previous verion.

**Comment by ilcato** [comment]
Added some logs. Can you redownload and test it?

**Comment by Gazous** [comment]
[6/12/2016, 9:34:37 PM] Homebridge is running on port 51826.
Plugin - DidFinishLaunching
[6/12/2016, 9:34:37 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/12/2016, 9:34:37 PM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +169ms
[6/12/2016, 9:34:38 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/12/2016, 9:34:38 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 9:34:38 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 9:35:40 PM] [FibaroHC2] Error fetching updates: null

Why is it just fetching 2 devices ?

**Comment by ilcato** [comment]
Try again please: redownload and test it.

**Comment by Gazous** [comment]
Seems Better but just create first devices, normal ?

Plugin - DidFinishLaunching
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/12/2016, 10:36:19 PM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +165ms
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Arrosage
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Store Banne
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Lampadaire
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Leds et Mirroir
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Spots
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Spots Meubles
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Température Plafond
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Rampe Spots
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Montgolfière
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Baby Monitor
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Suspension
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Suspension
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:19 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Lampadaire
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Spots SAM
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Spots Salon
[6/12/2016, 10:36:20 PM] [FibaroHC2] Fetched device: Mezanine

**Comment by ilcato** [comment]
No 😂

**Comment by Gazous** [comment]
Arg, I was thinking that you made a test to check something with first devices :-)

**Comment by ilcato** [comment]
Please test again. I added some more logs (remember to refresh the browser before downloading the index.js file).

**Comment by Gazous** [comment]
Plugin - DidFinishLaunching
[6/12/2016, 10:55:23 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/12/2016, 10:55:23 PM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +166ms
[6/12/2016, 10:55:23 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Arrosage
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Arrosage
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Arrosage
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Store Banne
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Store Banne
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Store Banne
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Leds et Mirroir
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Leds et Mirroir
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Leds et Mirroir
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Spots Meubles
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Spots Meubles
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Spots Meubles
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température Plafond
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température Plafond
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température Plafond
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Rampe Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Rampe Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Rampe Spots
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Porte
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Montgolfière
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Montgolfière
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Montgolfière
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Baby Monitor
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Baby Monitor
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Baby Monitor
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Lampe
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Suspension
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Plafonnier
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Température
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Lampadaire
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Spots SAM
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Spots SAM
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Spots SAM
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Spots Salon
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Spots Salon
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Spots Salon
[6/12/2016, 10:55:24 PM] [FibaroHC2] Fetched device: Mezanine
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 0 device: Mezanine
[6/12/2016, 10:55:24 PM] [FibaroHC2] Test 1 device: Mezanine

**Comment by ilcato** [comment]
Please test it again. I solved a bug for the configuration param "grouping" that doesn't have a default value, it should be "none".

**Comment by Gazous** [comment]
Hey, seems to work !!!

Plugin - DidFinishLaunching
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[6/12/2016, 11:04:59 PM] [FibaroHC2] Server Listening...
  EventedHTTPServer Server listening on port 51826 +164ms
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetching Fibaro Home Center devices ...
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 1 device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 2 device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetched device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Creating accessory: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Adding Accessory: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 1 device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 2 device: Porte
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetched device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 0 device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 1 device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 2 device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 3 device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Creating accessory: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 4 device: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Adding Accessory: Arrosage
[6/12/2016, 11:04:59 PM] [FibaroHC2] Fetched device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 0 device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 1 device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 2 device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 3 device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Creating accessory: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Test 4 device: Store Banne
[6/12/2016, 11:04:59 PM] [FibaroHC2] Adding Accessory: Store Banne
.......

**Comment by Gazous** [comment]
I just removed the test logs and it seems to be OK and you know what it's also working from outside using AppleTV4 as gateway. I never managed to have it work before !

**Comment by ilcato** [comment]
Let me tune a little bit and I will send you a final version to test.

**Comment by Gazous** [comment]
Of course ! Thanks a lot !
Hope this version will not make my HC2 crash every 24hours...

**Comment by ilcato** [comment]
If you are experiencing such a problem try to put into the config.json a parameter named "pollerperiod" with a value > than "5" that is the default value. In my case I'm working without problems with a value of "2" but maybe your HC2 con is different. The plugin executes a check with HC2 every "pollerperiod" seconds in order to verify changes in devices property values. Off course the smaller the parameters is the better the updates of Homekit apps is.

You can now test it. I will publish the new version as soon as you confirm me its correctness.

**Comment by Gazous** [comment]
OK, in the comments, you say that default polling value is 2...

**Comment by ilcato** [comment]
Thx

**Comment by Gazous** [comment]
Everything is up to date and running with a 2 seconds polling intervall.
I will give you so news in 2 days if you are OK

**Comment by ilcato** [comment]
ok

**Comment by Gazous** [comment]
Hi Ilcato, this night, HC2 crashed with a 503 error.
I will try to set polling intervall to 5 seconds and let you know...

**Comment by ilcato** [comment]
where did you see the 503 error?

**Comment by Gazous** [comment]
On my HC2 !

**Comment by ilcato** [comment]
On the web interface?

**Comment by Gazous** [comment]
Yes

**Comment by Gazous** [comment]
Hello Ilcato, With 5 seconds, same crash about 5 days later...

**Comment by ilcato** [comment]
Strange, it is something related to your (and a small number of other) specific configuration.
I had the refresh running with 2 seconds for more than a month.
Can you try to disable it completely (set the parameter to 0) in order to understand if it is really it the problem.
With 0 you loose the automatic update of the UI of the Homekit app but in most use cases it is not necessary.

**Comment by Gazous** [comment]
Ok, done !
You have to know that in a "normal" use I have a 503 error each month...
Home bridge refresh just make it happen earlier

**Comment by ilcato** [comment]
This is not normal. Did you have some strange devices? Plugins?

**Comment by Gazous** [comment]
No strange devices, only Fibaro and some Remotes.
i do not use plugins but some personal scenes

**Comment by ilcato** [comment]
What about CPU and memory consumption when you approach the critical time?

**Comment by Gazous** [comment]
My CPU never exceeds 20% and my RAM 68%.
But when crash occurs, I do not have the latest values...

**Comment by ilcato** [comment]
@Gazous, Fibaro just published an update (4.083) that mentions the 503 error that may appear when running multiple Virtual Devices simultaneously; the update fixes this problem. I think that you may have this case. Try to upgrade, it is a beta ...

**Comment by Gazous** [comment]
Ho ilcato, thanks for the information but I will wait for a release to update to this version...

**Comment by ilcato** [comment]
I published a new version with contains the fix. Closing issue.

**Comment by ilcato** [comment]
@Gazous : Fibaro just published version 4.090. It is not a beta and should solve your problem.

**Comment by Gazous** [comment]
Yes i has seen that ans will install it this weekend !
Thanks !
