### ISSUE TITLE
Pollerperiod error

### ISSUE THREAD

**Issue by mbnn** [ilcato/homebridge-Fibaro-HC2#133]
```
/homebridge/node_modules/homebridge-fibaro-hc2/src/index.ts:113
                let pollerPeriod = this.config.pollerperiod ? parseInt(this.config.pollerperiod) : defaultPollerPeriod;
                                 ^
TypeError: Cannot read property 'pollerperiod' of null
    at new FibaroHC2 (/homebridge/node_modules/homebridge-fibaro-hc2/src/index.ts:113:34)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:347:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Any idea? New install with homebridge on a Synology NAS.

**Comment by ilcato** [comment]
Where did you put config.json?

**Comment by mbnn** [comment]
In the default path where the other Homebridge plugin also is:

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
    "accessories": [],
    "platforms": [
        {
            "platform": "homebridge-plex-sensors.Plex",
            "sensors": [
                {
                    "name": "Plex",
                    "users": [
                        "username"
                    ]
                },
                {
                    "platform": "FibaroHC2",
                    "name": "FibaroHC2",
                    "host": "192.168.1.46",
                    "username": "user",
                    "password": "pass",
                    "securitysystem": "disabled",
                    "switchglobalvariables": ""
                }
            ]
        }
    ]
}

`

**Comment by ilcato** [comment]
It seems to me that you not closing the ] for the property sensors for the plugin Plex.

**Comment by mbnn** [comment]
I'm a noob :P  Placed the config wrong, my bad! It's fixed now :)
