### ISSUE TITLE
SecuritySystem

### ISSUE THREAD

**Issue by odenisenko** [ilcato/homebridge-Fibaro-HC2#152]
is subj is enabled then 
```
[2019-5-17 22:33:36] [FibaroHC2] Error getting data from Home Center:  TypeError: Cannot read property 'zwaveCompany' of undefined
    at ShadowAccessory.initAccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/shadows.js:44:52)
    at FibaroHC2.addAccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:195:25)
    at FibaroHC2.LoadAccessories (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:153:15)
    at fibaroClient.getScenes.then.then (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:103:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:808) UnhandledPromiseRejectionWarning: Error: Startup error: get scenes or devices
    at fibaroClient.getScenes.then.then.catch (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:108:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
as workaround, I have to add 
```
let device = { name: "FibaroSecuritySystem", roomID: 0, id: 0, properties: {zwaveCompany: ""} };..
```

**Comment by ilcato** [comment]
please make a Pull Request

**Comment by ilcato** [comment]
It should be ok now.
