### ISSUE TITLE
Error exception on load

### ISSUE THREAD

**Issue by carlittoer** [ilcato/homebridge-Fibaro-HC2#157]
[FibaroHC2] Error getting data from Home Center:  TypeError: Cannot read property 'zwaveCompany' of undefined
    at ShadowAccessory.initAccessory (/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/shadows.js:44:52)
    at FibaroHC2.addAccessory (/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:190:25)
    at FibaroHC2.LoadAccessories (/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:149:18)
    at fibaroClient.getScenes.then.then (/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:103:18)
    at <anonymous>:null:null
    at process._tickCallback (internal/process/next_tick.js:118:7)

**Comment by carlittoer** [comment]
HI I am trying to install the latest 2.2.4 and upon restart i get the following.

**Comment by ilcato** [comment]
@carlittoer, is the problem still present?

**Comment by carlittoer** [comment]
Nope. fixed.
