### ISSUE TITLE
Error: connect ENETUNREACH

### ISSUE THREAD

**Issue by odenisenko** [ilcato/homebridge-Fibaro-HC2#162]
if FibaroHC up _after_ homebridge - FibaroHC2 stopped unexpectedly 

```
[7/18/2019, 4:17:44 AM] [FibaroHC2] didFinishLaunching.
[7/18/2019, 4:17:45 AM] Homebridge is running on port 51826.
[7/18/2019, 4:17:45 AM] [FibaroHC2] Error getting data from Home Center:  { Error: connect ENETUNREACH 192.168.1.36:
80 - Local (0.0.0.0:0)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at defaultTriggerAsyncIdScope (net.js:971:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '192.168.1.36',
  port: 80 }
```

**Comment by ilcato** [comment]
@odenisenko, please check if you can reach the home center from the homebridge machine-

**Comment by ilcato** [comment]
Closing it. Reopen if you have updates
