### ISSUE TITLE
Error getting data from Home Center

### ISSUE THREAD

**Issue by saschaspeidel** [ilcato/homebridge-Fibaro-HC2#195]
After updating to the latest versions the HC2 Plugin is not working.
Node: v12.18.2
npm: 6.14.6

Startup-Log:

```
Jul 08 13:41:05 raspi-smarthome homebridge[2113]: [7/8/2020, 13:41:05] [FibaroHC2] didFinishLaunching.
Jul 08 13:41:06 raspi-smarthome homebridge[2113]: [7/8/2020, 13:41:06] [FibaroHC2] Loading accessories
Jul 08 13:41:06 raspi-smarthome homebridge[2113]: [7/8/2020, 13:41:06] [FibaroHC2] Error getting data from Home Center:  TypeError: Cannot read property 'getCharacteristic' of undefined
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at /usr/lib/node_modules/homebridge/src/server.ts:512:32
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at Array.map (<anonymous>)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at Server.handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:506:40)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at HomebridgeAPI.emit (events.js:315:20)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at HomebridgeAPI.registerPlatformAccessories (/usr/lib/node_modules/homebridge/src/api.ts:316:10)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at ShadowAccessory.registerUpdateAccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/src/shadows.ts:112:8)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at FibaroHC2.addAccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:253:19)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at /usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:194:10
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at Array.map (<anonymous>)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at FibaroHC2.LoadAccessories (/usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:191:11)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]: (node:2113) UnhandledPromiseRejectionWarning: Error: Startup error: get scenes or devices
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at /usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:160:11
Jul 08 13:41:06 raspi-smarthome homebridge[2113]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jul 08 13:41:06 raspi-smarthome homebridge[2113]: (node:2113) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-r
Jul 08 13:41:06 raspi-smarthome homebridge[2113]: (node:2113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I have no clue what to do. Can you help?

Cheers,
Sascha

**Comment by saschaspeidel** [comment]
Why so ever there were two installations of the plugin. Sorry that i bothered you.
