### ISSUE TITLE
Switch Global Variables error

### ISSUE THREAD

**Issue by ankitseal** [ilcato/homebridge-Fibaro-HC2#196]
Assigned 2 global variables as a list and this is the error as per the logs

```
Error getting data from Home Center:  TypeError: this.config.switchglobalvariables.split is not a function
    at FibaroHC2.LoadAccessories (/usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:222:60)
    at /usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:166:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10699) UnhandledPromiseRejectionWarning: Error: Startup error: get scenes or devices
    at /usr/lib/node_modules/homebridge-fibaro-hc2/src/index.ts:170:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10699) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10699) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ankitseal** [comment]
should have checked the code for the format
