### ISSUE TITLE
Security Alert message from Fibaro HC2 with V2.4.1

### ISSUE THREAD

**Issue by Franco268** [ilcato/homebridge-Fibaro-HC2#213]
Hi, I'm new but if I can help...

I got that mail from my HC2 with V2.4.1:

Security Alert:
Suspicious Login Attempts Prevented

--
We noticed 5 failed login attempts to your HC2-028966 that seemed suspicious.   				For your security, the following IP address: 192.168.100.2 has been locked for 30 minutes.

**Comment by jlborggreve** [comment]
Same here - running with HCL, homebridge v1.3.1, running on docker (ubuntu bionic beaver (18.04.5 LTS)

**Comment by neilpatel121** [comment]
Facing issue with authentication too, password is correct

[2/27/2021, 8:21:18 PM] [FibaroHC2] Error getting data from Home Center:  Error: Unauthorized
    at Request.callback (/usr/lib/node_modules/homebridge-fibaro-hc2/node_modules/superagent/src/node/index.js:879:15)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-fibaro-hc2/node_modules/superagent/src/node/index.js:1130:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  status: 401,
  response: <ref *1> Response {
    _events: [Object: null prototype] {},
    _eventsCount: 0,

**Comment by ilcato** [comment]
Reverted, latest changes. Upgrade to 2.4.2.

**Comment by neilpatel121** [comment]
Cheers for the swift response, that's working fine now
