### ISSUE TITLE
[FibaroHC2] Error fetching updates: null

### ISSUE THREAD

**Issue by raess1** [ilcato/homebridge-Fibaro-HC2#31]
When I try to start Homebridge it stuck for a while- then i get 
[FibaroHC2] Error fetching updates: null.

Robins-Mac-Pro:~ Robin$ homebridge
[2016-09-29 08:50:57] Loaded plugin: homebridge-fibaro-hc2
[2016-09-29 08:50:57] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2016-09-29 08:50:57] ---
[2016-09-29 08:50:57] Loaded config.json with 0 accessories and 1 platforms.
[2016-09-29 08:50:57] ---
[2016-09-29 08:50:57] Loading 1 platforms...
[2016-09-29 08:50:57] [FibaroHC2] Initializing FibaroHC2 platform...
[2016-09-29 08:50:57] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Plugin - DidFinishLaunching
[2016-09-29 08:50:57] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[2016-09-29 08:50:57] [FibaroHC2] Server Listening...
[2016-09-29 08:50:57] Homebridge is running on port 52280.
[2016-09-29 08:50:57] [FibaroHC2] Fetching Fibaro Home Center devices ...
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Fasad fram
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Fasadbelysning bak
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Fasad terras
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Belysning trädgård
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Fönsterlampa 2
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Fönsterlampa 1
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Ytterdörr lampa
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Entrédörr
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Lås
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Takspots 2
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Takspots 
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Badrum ljus
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Badrum tak
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Badrum spegel
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Badrum Rörelse
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Badrum temperatur
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 12.0
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 75.0
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 12.0.1
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 12.0.2
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 75.2
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Philips TV
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Sovrum tak
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Kontorbelysning
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 5.0.2
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 5.0
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: 5.0.1
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Hemma
[2016-09-29 08:50:57] [FibaroHC2] Adding Accessory: Evelina Iphone
[2016-09-29 08:52:17] [FibaroHC2] Error fetching updates: null

**Comment by ilcato** [comment]
Is this the first time you are using homebridge? Was it working before?

**Comment by raess1** [comment]
Yes/No. I use it with success on my mac laptop. But now i tried to install it on my mac desktop. 
I run hc2: 4.092

On laptop: Node -v 4.4.1
On laptop: Node -v 4.6.0

**Comment by ilcato** [comment]
It may be a problem of node version. I'm using "promises" in the plugin and don't know if it is supported on 4.4.1. Try to upgrade, I'm on 6.6.0 on my mac and it works flawlessly.

**Comment by raess1** [comment]
I updated to node -v 6.6.0
now I get error:


Robins-Mac-Pro:~ Robin$ homebridge
[2016-09-29 09:55:55] Loaded plugin: homebridge-fibaro-hc2
[2016-09-29 09:55:55] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2016-09-29 09:55:55] ---
[2016-09-29 09:55:55] Loaded config.json with 0 accessories and 1 platforms.
[2016-09-29 09:55:55] ---
[2016-09-29 09:55:55] Loading 1 platforms...
[2016-09-29 09:55:55] [FibaroHC2] Initializing FibaroHC2 platform...
[2016-09-29 09:55:55] Loading 0 accessories...
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Fasad fram
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Fasadbelysning bak
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Fasad terras
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Belysning trädgård
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Fönsterlampa 2
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Fönsterlampa 1
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Ytterdörr lampa
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Entrédörr
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Lås
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Takspots 2
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Takspots 
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Badrum ljus
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Badrum tak
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Badrum spegel
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Badrum Rörelse
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Badrum temperatur
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 12.0
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 75.0
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 12.0.1
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 12.0.2
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 75.2
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Philips TV
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Sovrum tak
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Kontorbelysning
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 5.0.2
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 5.0
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: 5.0.1
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Hemma
[2016-09-29 09:55:55] [FibaroHC2] Configuring Accessory: Evelina Iphone
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/Users/Robin/.homebridge/persist/AccessoryInfo.AC223DE3CE30.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.persistKeySync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:457:12)
    at Object.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/local-storage.js:275:14)
    at Object.nodePersist.setItemSync (/usr/local/lib/node_modules/homebridge/node_modules/node-persist/node-persist.js:99:29)
    at AccessoryInfo.save (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:160:11)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:439:23)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:10)
Robins-Mac-Pro:~ Robin$

**Comment by ilcato** [comment]
Try to remove the persist and accessories folders

**Comment by raess1** [comment]
Persist and accessories folder removed.
Run Homebridge again:

error:

Robins-Mac-Pro:~ Robin$ homebridge
[2016-09-29 10:00:12] Loaded plugin: homebridge-fibaro-hc2
[2016-09-29 10:00:12] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2016-09-29 10:00:12] ---
[2016-09-29 10:00:12] Loaded config.json with 0 accessories and 1 platforms.
[2016-09-29 10:00:12] ---
[2016-09-29 10:00:12] Loading 1 platforms...
[2016-09-29 10:00:12] [FibaroHC2] Initializing FibaroHC2 platform...
[2016-09-29 10:00:12] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Plugin - DidFinishLaunching
[2016-09-29 10:00:12] [FibaroHC2] Fetching Fibaro Home Center rooms ...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51827
    at Object.exports._errnoException (util.js:1036:11)
    at exports._exceptionWithHostPort (util.js:1059:20)
    at Server._listen2 (net.js:1252:14)
    at listen (net.js:1288:10)
    at Server.listen (net.js:1384:5)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:59:19)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:157:20)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/local/lib/node_modules/homebridge/lib/server.js:111:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:10)
Robins-Mac-Pro:~ Robin$

**Comment by ilcato** [comment]
you have a previous instance of home bridge running. Kill it before re-executing homebridge

**Comment by raess1** [comment]
How do I kill it?

**Comment by ilcato** [comment]
Use activity monitor or type `ps aux|grep homebridge` on a terminal and then `kill -9 pid` where pid is the process number listed on the previous command (the second field)

**Comment by raess1** [comment]
Thanks. I did as you said and run it again.
Now it´s only stuck.

Robins-Mac-Pro:~ Robin$ homebridge
[2016-09-29 10:38:50] Loaded plugin: homebridge-fibaro-hc2
[2016-09-29 10:38:50] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2016-09-29 10:38:50] ---
[2016-09-29 10:38:50] Loaded config.json with 0 accessories and 1 platforms.
[2016-09-29 10:38:50] ---
[2016-09-29 10:38:50] Loading 1 platforms...
[2016-09-29 10:38:50] [FibaroHC2] Initializing FibaroHC2 platform...
[2016-09-29 10:38:50] Loading 0 accessories...
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Fasad fram
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Fasadbelysning bak
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Fasad terras
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Belysning trädgård
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Fönsterlampa 2
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Fönsterlampa 1
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Ytterdörr lampa
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Entrédörr
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Lås
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Takspots 2
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Takspots 
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Badrum ljus
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Badrum tak
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Badrum spegel
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Badrum Rörelse
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Badrum temperatur
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 12.0
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 75.0
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 12.0.1
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 12.0.2
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 75.2
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Philips TV
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Sovrum tak
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Kontorbelysning
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 5.0.2
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 5.0
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: 5.0.1
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Hemma
[2016-09-29 10:38:50] [FibaroHC2] Configuring Accessory: Evelina Iphone
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Plugin - DidFinishLaunching
[2016-09-29 10:38:50] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[2016-09-29 10:38:50] [FibaroHC2] Server Listening...
[2016-09-29 10:38:50] Homebridge is running on port 51827.
[2016-09-29 10:38:50] [FibaroHC2] Fetching Fibaro Home Center devices ...

**Comment by ilcato** [comment]
It's not stucked. After loading cached accessories it tries to find new devices without finding it.
It is ready.
Go to the iOs side and look for the new homebridge instance.

**Comment by raess1** [comment]
thanks :-)
Now I have another problem, Home app is telling me "Cloud Data Sync In Progress"
However I guess it´s not a problem with this bridge;P

**Comment by ilcato** [comment]
Which version of iOS do you have?

**Comment by raess1** [comment]
10.0.1

**Comment by ilcato** [comment]
I think that you need to wait.
Try to logout from iCloud on the device.

**Comment by raess1** [comment]
I guess we can mark this solved for the homebridge:)
So the problem with Home app "Cloud Data Sync In Progress" also solved after hours testing different things. It seems to be big problem according to the Apple help forum (and without any proper solution). This problem is also named: home app stuck loading accessories and scenes.

What i tried:
1. a brand new icloud account.
2. log out and log in on the iCloud account (all devices)
3. Resetting the network settings
4. Factory settings.
5. keychain off / on
6. Router reboot

Anyways, the solution,
1. Get an old iOS device without iOS 10
2. login to your iCloud on the old device.
3. Add homebridge on the old device.
4. On the New device Press home app and done.


thanks for the help @ilcato :-)
