### ISSUE TITLE
DNS Service Error: name conflict

### ISSUE THREAD

**Issue by marzjr** [ilcato/homebridge-Fibaro-HC2#41]
I have installed homebridge by nfarina and fibaro homebridge plugin by ilcato.
Than i try to running hommebridge, but come with error like below

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[11/1/2016, 8:10:19 AM] Loaded plugin: homebridge-fibaro-hc2
[11/1/2016, 8:10:19 AM] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[11/1/2016, 8:10:19 AM] ---
[11/1/2016, 8:10:19 AM] Loaded config.json with 0 accessories and 1 platforms.
[11/1/2016, 8:10:19 AM] ---
[11/1/2016, 8:10:19 AM] Loading 1 platforms...
[11/1/2016, 8:10:19 AM] [FibaroHC2] Initializing FibaroHC2 platform...
[11/1/2016, 8:10:20 AM] Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Plugin - DidFinishLaunching
[11/1/2016, 8:10:20 AM] [FibaroHC2] Fetching Fibaro Home Center rooms ...
[11/1/2016, 8:10:20 AM] [FibaroHC2] Server Listening...
/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/hap-nodejs/lib/HAPServer.js:184:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)

Log says  Error: dns service error: name conflict
How to solve this error?
Please help and advise. Thanks

**Comment by marzjr** [comment]
node.js : V.4.0.0 , homebridge: 0.4.6, homebridge-fibaro-hc2: 0.7.0.
I run this homebridge on Raspberry PI

**Comment by ilcato** [comment]
Upgrade node.js to at least 6.x. Reinstall homebridge.

**Comment by marzjr** [comment]
Solved now.. Big Thanks!!
