### ISSUE TITLE
UUID errors

### ISSUE THREAD

**Issue by amatt09** [ilcato/homebridge-Fibaro-HC2#47]
I am basically getting the following UUID errors when trying to run fibaro homebridge and i am on version 4.110. i have posted the error below.

*I do have two light bulbs (main light) that i have combined in fibaro to act as one light. Does not know if this is causing the error. Please help!

[1/8/2017, 12:16:55 PM] Initializing FibaroHC2 platform...
[1/8/2017, 12:16:55 PM] [FibaroHC2] Initializing FibaroHC2 platform...
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Motion Sensor
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Bed Sensor
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Light
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Door Sensor
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Door Temp
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Door Lux
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Bed Light right
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Temp
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Lux
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Humidity
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Fan
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Bed Light left
[1/8/2017, 12:16:55 PM] [FibaroHC2] Configuring Accessory: Main Motion Sensor
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: a9e36d7c-5d44-4c71-9d67-7ae8bf98e7d9
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:222:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:348:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:83:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

**Comment by ilcato** [comment]
Which version of the plugin did you install?

**Comment by amatt09** [comment]
whatever install this site has below. how can i install the latest version if this is not current?


https://www.npmjs.com/package/homebridge-fibaro-hc2 <https://www.npmjs.com/package/homebridge-fibaro-hc2>

**Comment by ilcato** [comment]
Check with:
`sudo npm list -g | grep fibaro`

**Comment by amatt09** [comment]
this is the output.

├─┬ homebridge-fibaro-hc2@1.0.2

**Comment by ilcato** [comment]
Do you have 2 or more devices with the same name in the same room?
Try to delete the accessories folder.

**Comment by amatt09** [comment]
i have two bulbs named “Main Light” and “Main Light 1”. i have un grouped them and still get same results.

**Comment by ilcato** [comment]
Did you try to remove accessories folder? (it's in the same directory as config.json)

**Comment by ilcato** [comment]
any news?

**Comment by amatt09** [comment]
Sorry haven’t had time to test. i will test this weekend and report back thanks

**Comment by amatt09** [comment]
Still did not work same errors

**Comment by ilcato** [comment]
what do you mean with:

i have un grouped them

?

**Comment by amatt09** [comment]
with fibaro you can make two devices act as one controllable device. I have split them up so they are no longer considered one device. Does this make sense? i don’t think this would have any effect on why it is giving me errors.

**Comment by ilcato** [comment]
Try to:

- rename "Main Light 1” in "_Main Light 1”
- remove accessories folder
- start homebridge

**Comment by amatt09** [comment]
ok so i changed the main light name and removed the accessories folder then started home bridge. the only error it gave was "Error getting data from Home Center: Error: getaddrinfo ENOTFOUND 192. 192.:80 undefined”

then i stopped the process and then started homebridge again with the accessories folder it created automatically from the last run and gave me the UUID error again.

**Comment by ilcato** [comment]
Try again please removing accessories folder after stopping homebridge and starting it again. The first error is something related to a config problem, did you change the hc address in config.json?

**Comment by amatt09** [comment]
got it to work. come to find out that the config file had two instances of fibaro platform. fixed that then it still gave the error, and looked at the config file again and found that the ip address had a space in it. working now thanks for all the help.
