### ISSUE TITLE
[FibaroHC2] didFinishLaunching.

### ISSUE THREAD

**Issue by 10der** [ilcato/homebridge-Fibaro-HC2#68]
recently (re)installed apps
pi@smarthome:~/.homebridge $ node -v
v8.1.3

======================================================
[2017-7-8 19:30:56] [FibaroHC2] Initializing FibaroHC2 platform...
[2017-7-8 19:30:56] Loading 1 accessories...
[2017-7-8 19:30:56] [Home security] Initializing Http-SecuritySystem accessory...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-154 │
    └────────────┘

[2017-7-8 19:30:56] [FibaroHC2] didFinishLaunching.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server.setupListenHandle [as _listen2] (net.js:1315:14)
    at listenInCluster (net.js:1363:12)
    at Server.listen (net.js:1463:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:486:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:10)
pi@smarthome:~/.homebridge $

**Comment by 10der** [comment]
oops!!!
sorry. my fail - another copy was running.
fixed!
