### ISSUE TITLE
trap on  Added/changed accessory

### ISSUE THREAD

**Issue by 10der** [ilcato/homebridge-Fibaro-HC2#69]
[2017-7-8 19:44:37] [FibaroHC2] Error getting data from Home Center:  TypeError: Cannot read property 'getCharacteristic' of undefined
    at Accessory._sideloadServices (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:857:5)
    at PlatformAccessory._prepareAssociatedHAPAccessory (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:148:32)
    at Server._handleRegisterPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:431:15)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:36:10)
    at emitOne (events.js:115:13)
    at API.emit (events.js:210:7)
    at API.registerPlatformAccessories (/usr/lib/node_modules/homebridge/lib/api.js:159:8)
    at ShadowAccessory.resgisterUpdateccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/shadows.js:88:17)
    at FibaroHC2.addAccessory (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:166:25)
    at LoadAccessories.devices.map (/usr/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:113:22)

**Comment by 10der** [comment]
IMHO stopped here

`
{
id: 11,
name: "Сейсмометр",
roomID: 5,
type: "com.fibaro.seismometer",
baseType: "com.fibaro.multilevelSensor",
enabled: true,
visible: true,
isPlugin: false,
parentId: 7,
remoteGatewayId: 0,
viewXml: false,
configXml: false,
interfaces: [
"battery",
"zwave",
"zwaveWakeup"
],
properties: {
batteryLevel: 88,
pollingTimeSec: 0,
wakeUpTime: 4000,
zwaveCompany: "Fibargroup",
zwaveInfo: "3,4,5",
zwaveVersion: "3.2",
batteryLowNotification: "true",
configured: "true",
dead: "false",
defInterval: "0",
deviceControlType: "0",
deviceIcon: "89",
emailNotificationID: "0",
emailNotificationType: "0",
endPointId: "0",
liliOffCommand: "",
liliOnCommand: "",
log: "",
logTemp: "",
manufacturer: "",
markAsDead: "true",
maxInterval: "0",
minInterval: "0",
model: "",
nodeId: "3",
parametersTemplate: "712",
productInfo: "1,15,8,1,16,1,3,2",
pushNotificationID: "0",
pushNotificationType: "0",
remoteGatewayId: "0",
saveLogs: "true",
serialNumber: "h'000000000004a264",
smsNotificationID: "0",
smsNotificationType: "0",
stepInterval: "0",
unit: "MMI",
useTemplate: "true",
userDescription: "",
value: "0.00"
},
actions: {
reconfigure: 0,
setInterval: 1
},
created: 1498835950,
modified: 1498835950,
sortOrder: 12
},
`

**Comment by 10der** [comment]
`
    addAccessory(shadowAccessory) {
        if (shadowAccessory == undefined)
            return;
	this.log("Trying to Added/changed accessory: ", shadowAccessory.name);
`

[2017-7-8 20:11:36] [FibaroHC2] Trying to Added/changed accessory:  Outdoors sensors
[2017-7-8 20:11:36] [FibaroHC2] Error getting data from Home Center:  TypeError: Cannot read property 'getCharacteristic' of undefined

btw Outdoors sensors - VD

**Comment by 10der** [comment]
so. I have temporarily disabled loading virtual_device(s) in Load Accessories(devices) method
`if (s.type != "virtual_device")`

now, all OK.


please, fix it ASAP.

thank you!

**Comment by ilcato** [comment]
The problem will be fixed in an upcoming release. 
It is related to a vd without buttons. In the mean time try to exclude such a vd by prepending an _ to its name or via a user without visibility on it.
