### ISSUE TITLE
Unable to read config file

### ISSUE THREAD

**Issue by CryogenicPilot** [ilcato/homebridge-Fibaro-HC2#71]
Hi,

after writing the correct parameters on config.json inside ~/.homebridge/config.json I experience this error:

```
[8/14/2017, 12:24:19 PM] Loading 2 platforms...
[8/14/2017, 12:24:19 PM] [eDomoticz] Initializing eDomoticz platform...
[8/14/2017, 12:24:19 PM] Initializing Camera-ffmpeg-omx platform...
[8/14/2017, 12:24:19 PM] Loading 0 accessories...
Load homebridge-fibaro-hc2.FibaroHC2
/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:55
        let pollerPeriod = this.config.pollerperiod ? parseInt(this.config.pollerperiod) : defaultPollerPeriod;
                                      ^

TypeError: Cannot read property 'pollerperiod' of null
    at new FibaroHC2 (/usr/local/lib/node_modules/homebridge-fibaro-hc2/dist/index.js:55:39)
    at Server._loadDynamicPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:315:30)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:82:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

It seems not able to read config file.

Any suggestion?

**Comment by ilcato** [comment]
Which version of homebridge and node.js do you have?

**Comment by ilcato** [comment]
Should be fixed in the just published release.
