### ISSUE TITLE
ETIMEDOUT

### ISSUE THREAD

**Issue by michalboryka** [ilcato/homebridge-Fibaro-HC2#75]
Hi, 

clean installation, no problems at all but still getting: 
[2017-11-4 00:35:27] Loaded plugin: homebridge-fibaro-hc2
[2017-11-4 00:35:27] Registering platform 'homebridge-fibaro-hc2.FibaroHC2'
[2017-11-4 00:35:27] ---
[2017-11-4 00:35:27] Loaded config.json with 0 accessories and 1 platforms.
[2017-11-4 00:35:27] ---
[2017-11-4 00:35:27] Loading 1 platforms...
[2017-11-4 00:35:27] [FibaroHC2] Initializing FibaroHC2 platform...
[2017-11-4 00:35:27] Loading 0 accessories...
Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
                                
[2017-11-4 00:35:27] [FibaroHC2] didFinishLaunching. 
[2017-11-4 00:35:27] Homebridge is running on port 51826.
[2017-11-4 00:37:41] [FibaroHC2] Error getting data from Home Center:  { Error: connect ETIMEDOUT 192.167.1.7:80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'ETIMEDOUT',

**Comment by michalboryka** [comment]
node 4.9.2 did the job
